export const materialsData = [
    { id: "1",value: "Có trách nhiệm" },
    { id: "2",value: "Thành tựu" },
    { id: "3",value: "Khả năng thích ứng" },
    { id: "4",value: "Phiêu lưu" },
    { id: "5",value: "Lòng vị tha" },
    { id: "6",value: "Tham vọng" },
    { id: "7",value: "Chân thực" },
    { id: "8",value: "Cân bằng" },
    { id: "9",value: "Cái đẹp" },
    { id: "10",value: "Là người giỏi nhất" },
    { id: "11",value: "Thuộc về" },
    { id: "12",value: "Sự nghiệp" },
    { id: "13",value: "Quan tâm" },
    { id: "14",value: "Cộng tác" },
    { id: "15",value: "Cam kết" },
    { id: "16",value: "Cộng đồng" },
    { id: "17",value: "Lòng trắc ẩn" },
    { id: "18",value: "Năng lực" },
    { id: "19",value: "Sự tự tin" },
    { id: "20",value: "Kết nối" },
    { id: "21",value: "Hài lòng" },
    { id: "22",value: "Sự đóng góp" },
    { id: "23",value: "Hợp tác" },
    { id: "24",value: "Lòng can đảm" },
    { id: "25",value: "Sáng tạo" },
    { id: "26",value: "Tò mò" },
    { id: "27",value: "Phẩm cách" },
    { id: "28",value: "Đa dạng" },
    { id: "29",value: "Môi trường" },
    { id: "30",value: "Tháo vát" },
    { id: "31",value: "Tôn trọng" },
    { id: "32",value: "Chịu trách nhiệm" },
    { id: "33",value: "Mạo hiểm" },
    { id: "34",value: "Sự an toàn" },
    { id: "35",value: "Vững chắc" },
    { id: "36",value: "Tự giác kỷ luật" },
    { id: "37",value: "Thể hiện bản thân" },
    { id: "38",value: "Tự trọng" },
    { id: "39",value: "An nhiên" },
    { id: "40",value: "Phục vụ" },
    { id: "41",value: "Hiệu quả" },
    { id: "42",value: "Bình đẳng" },
    { id: "43",value: "Đạo đức" },
    { id: "44",value: "Xuất sắc" },
    { id: "45",value: "Công bằng" },
    { id: "46",value: "Đức tin" },
    { id: "47",value: "Gia đình" },
    { id: "48",value: "Ổn định tài chính" },
    { id: "49",value: "Sự tha thứ" },
    { id: "50",value: "Tự do" },
    { id: "51",value: "Tình bạn" },
    { id: "52",value: "Vui vẻ" },
    { id: "53",value: "Thế hệ tương lai" },
    { id: "54",value: "Hào sảng" },
    { id: "55",value: "Cho đi" },
    { id: "56",value: "Bao dung" },
    { id: "57",value: "Lòng biết ơn" },
    { id: "58",value: "Sự phát triển" },
    { id: "59",value: "Hòa hợp" },
    { id: "60",value: "Sức khỏe" },
    { id: "61",value: "Mái ấm" },
    { id: "62",value: "Trung Thực" },
    { id: "63",value: "Hy vọng" },
    { id: "64",value: "Khiêm tốn" },
    { id: "65",value: "Hài hước" },
    { id: "66",value: "Không phân biệt" },
    { id: "67",value: "Độc lập" },
    { id: "68",value: "Sáng kiến" },
    { id: "69",value: "Chính trực" },
    { id: "70",value: "Mộc mạc" },
    { id: "71",value: "Tâm linh" },
    { id: "72",value: "Tinh thần thể thao" },
    { id: "73",value: "Quản lý có trách nhiệm" },
    { id: "74",value: "Thành công" },
    { id: "75",value: "Tinh thần đồng đội" },
    { id: "76",value: "Tiết kiệm" },
    { id: "77",value: "Thời gian" },
    { id: "78",value: "Truyền thống" },
    { id: "79",value: "Du lịch" },
    { id: "80",value: "Niềm tin" },
    { id: "81",value: "Sự thật" },
    { id: "82",value: "Trực giác" },
    { id: "83",value: "Công việc ổn định" },
    { id: "84",value: "Hân hoan" },
    { id: "85",value: "Công bằng" },
    { id: "86",value: "Tử tế" },
    { id: "87",value: "Kiến thức" },
    { id: "88",value: "Lãnh đạo" },
    { id: "89",value: "Học tập" },
    { id: "90",value: "Di sản" },
    { id: "91",value: "Giải trí" },
    { id: "92",value: "Tình yêu thương" },
    { id: "93",value: "Lòng trung thành" },
    { id: "94",value: "Tạo sự khác biệt" },
    { id: "95",value: "Tự nhiên" },
    { id: "96",value: "Cởi mở" },
    { id: "97",value: "Lạc quan" },
    { id: "98",value: "Trật tự" },
    { id: "99",value: "Nuôi dạy con" },
    { id: "100",value: "Kiên nhẫn" },
    { id: "101",value: "Yêu nước" },
    { id: "102",value: "Hòa bình" },
    { id: "103",value: "Kiên trì" },
    { id: "104",value: "Hoàn thành ước nguyện cá nhân" },
    { id: "105",value: "Quyền lực" },
    { id: "106",value: "Kiêu hãnh" },
    { id: "107",value: "Sự công nhận" },
    { id: "108",value: "Độ tin cậy" },
    { id: "109",value: "Thấu hiểu" },
    { id: "110",value: "Tính độc đáo" },
    { id: "111",value: "Sự hữu ích" },
    { id: "112",value: "Tầm nhìn" },
    { id: "113",value: "Dễ tổn thương" },
    { id: "114",value: "Sự giàu có" },
    { id: "115",value: "Bình an" },
    { id: "116",value: "Toàn tâm toàn ý" },
    { id: "117",value: "Trí tuệ" }
  ];
  

  